config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :posts
  root 'posts#index'
  get 'index' => 'posts#index'
  post 'index' => 'posts#index'
  get '/:name' => 'posts#user_posts', as: :user_posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
	belongs_to :user

	paginates_per 3
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  validates :username, presence: true, uniqueness: true
  validates :avatar, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(id: @comment.post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #
  def user_posts
    @user = User.find_by(username: params[:name])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :blog_entry, :user_id)
    end
end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
  def index
  	@name = params[:name]
  end

  def about
  	@color = params[:color]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= form.text_area :comment_entry, placeholder: "What's on your mind?", class: "form-control", rows: 6 %>

  <div class="pager">
    <%= form.submit "Add Comment", class: "btn btn-primary" %>
  </div>

  <%= form.hidden_field :post_id, value: @post.id %>
  <%= form.hidden_field :user_id, value: current_user.id %>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry.html_safe %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechTalentBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Navbar Start -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button> -->
          <a class="navbar-brand" href="<%= root_path %>">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <!-- <ul class="nav navbar-nav">
            <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Link</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form> -->
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="navbar-text">Welcome <%= current_user.username %></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <!-- Navbar End -->

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <div class="input-group">
        <span class="input-group-addon">Title</span>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <!-- <div class="input-group">
        <span class="input-group-addon">Author</span>
      </div> -->
      <%= form.text_area :blog_entry, placeholder: "Write your blog post here", class: "form-control", rows: 6 %>
      <div class="pager">
        <%= form.submit "Publish", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
 
<% end %>

app/views/posts/edit.html.erb
<br>
<br>

<%= render 'form', post: @post %>

<div class="pager">
	<div class="btn-group" role="group">
		<%= link_to 'View Comments', @post, class: "btn btn-primary btn-lg" %>
		<%= link_to 'Back to Index', posts_path, class: "btn btn-primary btn-lg" %>
	</div>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4">Blog</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
</div>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <% @posts.each do |post| %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <%= image_tag post.user.avatar.url, class: "thumbnail" %>
          <i>
            <%= link_to post.user.username, user_posts_path(name: post.user.username) %>
            <%= post.created_at.strftime("posted on %m/%d/%Y at %I:%M%p") %>
          </i>
          <h3 class="panel-title"><%= post.title %></h3>
        </div>
        <div class="panel-body">
          <%= post.blog_entry.html_safe %>
        </div>
        <div class="panel-footer">
          <div class="btn-group btn-group-justified" role="group">
            <%= link_to 'View Comments', post_path(post), class: "btn btn-primary"%>
            <% if current_user.id == post.user_id %>
              <%= link_to 'Edit Post', edit_post_path(post), class: "btn btn-primary" %>
              <%= link_to 'Delete Post', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="text-center">
  <%= paginate @posts %>
</div>

<div class="pager">
  <%= link_to 'New Post', new_post_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/posts/new.html.erb
<br>
<br>

<%= render 'form', post: @post %>

<div class="pager">
	<%= link_to 'Back to Index', posts_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-primary">
    <div class="panel-heading">
    	<%= image_tag @post.user.avatar.url, class: "thumbnail" %>
      <i>
      	<%= link_to @post.user.username, user_posts_path(name: @post.user.username) %>
      	<%= @post.created_at.strftime("posted on %m/%d/%Y at %I:%M%p") %>
      </i>
      <h3 class="panel-title"><%= @post.title %></h3>
    </div>
    <div class="panel-body">
      <%= @post.blog_entry.html_safe %>
    </div>
</div>

<div id="comments">
	<div class="row">
		<div class="col-md-3 col-sm-2 col-xs-1"></div>
		<div class="col-md-6 col-sm-8 col-xs-10">
			<%= render "comments/form", comment: @comment %>
			<% @post.comments.each do |comment| %>
				<div class="panel panel-info">
				  <div class="panel-heading">

				  	<%= image_tag comment.user.avatar.url, class: "thumbnail" %>

					  <i>
					  	<%= link_to comment.user.username, user_posts_path(name: comment.user.username) %>
					  	<%= comment.created_at.strftime("replied on %m/%d/%Y at %I:%M%p") %>
					  </i>
					</div>
				  <div class="panel-body">
				    <%= comment.comment_entry.html_safe %>
				  </div>
				</div>
			<% end %>
		</div>
		<div class="col-md-3 col-sm-2 col-xs-1"></div>
	</div>
</div>

<div class="pager">
	<div class="btn-group" role="group">
		<%= link_to 'Edit Post', edit_post_path(@post), class: "btn btn-primary btn-lg" %>
		<%= link_to 'Back to Index', posts_path, class: "btn btn-primary btn-lg" %>
	</div>
</div>

app/views/posts/user_posts.html.erb
<h1 class="text-center">All Posts by <%= @user.username %></h1>

<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <% @user.posts.each do |post| %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <%= image_tag post.user.avatar.url, class: "thumbnail" %>
          <i>
            <%= post.user.username %>
            <%= post.created_at.strftime("posted on %m/%d/%Y at %I:%M%p") %>
          </i>
          <h3 class="panel-title"><%= post.title %></h3>
        </div>
        <div class="panel-body">
          <%= post.blog_entry.html_safe %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/practice/about.html.erb
<style>
	#color_me_in {
	  background-color: <%= @color %>;
	  color: white;
	  width: 250px;
	  height: 250px;
	}
</style>

<div id="color_me_in">
	<p>
    <%= @color.upcase %> BOX ACTIVATED!
	</p>
</div>

<%= form_tag index_path do %>
  <p><%= text_field_tag :name, nil, placeholder: "What's your name?" %></p>
  <p><%= submit_tag :submit %></p>
<% end %>

app/views/practice/index.html.erb
<h1>Choose a Color!</h1>

<% if !@name.blank? %> <!-- if @name is not nil, blank, or empty -->
  <h2>Welcome Back, <%= @name %></h2>
<% end %>

<p>
	<%= link_to "Red", about_path(color: "red") %>
</p>

<p>
	<%= link_to "Blue", about_path(color: "blue") %>
</p>

<p>
	<%= link_to "Green", about_path(color: "green") %>
</p>

<p>
	<%= link_to "Yellow", about_path(color: "yellow") %>
</p>